# Generated by Django 2.1.8 on 2019-05-09 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0002_auto_20190502_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
