# Generated by Django 2.1.8 on 2019-05-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0003_blog_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
